let start = document.getElementById('start'),
	budget = document.getElementsByClass('budget-value'),
	daybudget = document.getElementsByClass('daybudget-value'),
	level = document.getElementsByClass('level-value'),
	expenses = document.getElementsByClass('expenses-value'),
	optionalexpenses = document.getElementsByClass('optionalexpenses-value'),
	income = document.getElementsByClass('income-value'),
	monthsavings = document.getElementsByClass('monthsavings-value'),
	yearsavings = document.getElementsByClass('yearsavings-value'),
	inp = document.getElementsByClass('expenses-item'),
	buttonOne = document.getElementByTagName('button'),
	buttonTwo = document.getElementByTagName('button'),
	optionalexpensesItem = document.querySelectorAll('.data .optionalexpenses-item'),
	chooseIncome = document.querySelector('.choose-income'),
	percent = document.querySelector('.choose-percent'),
	year = document.querySelector('.year-value'),
	month = document.querySelector('.month-value'),
	day = document.querySelector('.day-value'),
	sum = document.querySelector('.choose-sum'),
	savings = document.querySelector('.savings')

console.log(start);