let start = document.getElementById('start'),
	budget = document.getElementsByClassName('budget-value'),
	daybudget = document.getElementsByClassName('daybudget-value'),
	level = document.getElementsByClassName('level-value'),
	expenses = document.getElementsByClassName('expenses-value'),
	optionalexpenses = document.getElementsByClassName('optionalexpenses-value'),
	income = document.getElementsByClassName('income-value'),
	monthsavings = document.getElementsByClassName('monthsavings-value'),
	yearsavings = document.getElementsByClassName('yearsavings-value'),
	inp = document.getElementsByClassName('expenses-item'),
	buttonOne = document.getElementsByTagName('button'),
	buttonTwo = document.getElementsByTagName('button'),
	optionalexpensesItem = document.querySelectorAll('.data .optionalexpenses-item'),
	chooseIncome = document.querySelector('.choose-income'),
	percent = document.querySelector('.choose-percent'),
	year = document.querySelector('.year-value'),
	month = document.querySelector('.month-value'),
	day = document.querySelector('.day-value'),
	sum = document.querySelector('.choose-sum'),
	savings = document.querySelector('.savings')

console.log(optionalexpensesItem);